# Generated by Django 5.1.4 on 2026-03-09 10:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategori Produk',
                'verbose_name_plural': 'Kategori Produk',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_of_measure', models.CharField(choices=[('KG', 'Kilogram'), ('TON', 'Ton'), ('SAK', 'Sak (50kg)'), ('LTR', 'Liter'), ('UNIT', 'Unit')], default='SAK', max_length=10)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('current_stock', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('minimum_stock', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('maximum_stock', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Penerimaan Stok'), ('OUT', 'Pengeluaran Stok'), ('SALE', 'Penjualan'), ('PURCH', 'Pembelian'), ('ADJ_IN', 'Penyesuaian Masuk'), ('ADJ_OUT', 'Penyesuaian Keluar'), ('TRF_IN', 'Transfer Masuk'), ('TRF_OUT', 'Transfer Keluar'), ('RET_IN', 'Retur Masuk'), ('RET_OUT', 'Retur Keluar'), ('OPEN', 'Saldo Awal')], db_index=True, max_length=10)),
                ('movement_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('stock_before', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('stock_after', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pergerakan Stok',
                'verbose_name_plural': 'Pergerakan Stok',
                'ordering': ['-movement_date', '-created_at'],
                'abstract': False,
            },
        ),
    ]
